### ISSUE TITLE
How to get the Contact Page working?

### ISSUE THREAD

**Issue by FulI-Name** [nethruster/ptemplate#38]
I've been here wondering how to get the contact page working?
I've tried so many different things and none work. 
I just get "Connection Error"

**Comment by gariasf** [comment]
Hi @FulI-Name!

We'd love to help :)
It would be very helpful to see your currect template configuration and a screenshot where the error is shown. 
Can you please send more information about this issue?

**Comment by FulI-Name** [comment]
@gariasf so what excatly do you want?

**Comment by FulI-Name** [comment]
What files?

**Comment by FulI-Name** [comment]
Also the connection error happens when I press send

**Comment by Miguel-Dorta** [comment]
We need more information to troubleshoot it. Can you please, provide:

1. The backend you're using for handling the form

2. A screenshot of the error that the browser's console returns when you send the form. You can open the console in most browsers with F12 -> Console tab.

I'll put an example of a console error in chrome for you to know.

![Image of a console error in Chrome](https://i.nth.sh/media/4mM4w8KV46/aj4pvSgQQN.png)

**Comment by FulI-Name** [comment]
Okay, I got this error:
![image](https://user-images.githubusercontent.com/42716008/89149669-abdcaa00-d565-11ea-9d4d-9d2265912faa.png)

**Comment by FulI-Name** [comment]
Also idk what backend I'm using. Like I got confused what to do to get the email work. That part I was like ???

**Comment by FulI-Name** [comment]
Everything else was simple to setup. 👍

**Comment by Miguel-Dorta** [comment]
Oh, I see the problem. You need to have a backend up and running for the form contact to work. This is made this way for security reasons (if you want more info I'll explain it below).

If you know how to code it, I encourage you to make it yourself and put it wherever you like (a server, vps, cloud function...).

If you don't know how to code it, you can use [web-msg-handler](https://github.com/Miguel-Dorta/web-msg-handler). It's more complex to set up than ptemplate, and it's kind of slow at this moment (until I put more work in it), but it gets the work done.



Explanation of 'why is it required a backend for the contact form to work':
To send an email (via SMTP, for example) it is required a valid email username and password. Those are used to authenticate with a server (for example, with Google in case of GMail) and send the email. Since ptemplate is just pure frontend this information must be send to the client's browser for them to authenticate, and it's not secure at all to give every visitor of your web some email credentials.

**Comment by Miguel-Dorta** [comment]
I think I need to make it clear. We are thinking in making a second version of ptemplate in the future, and these concerns will probably be addressed and we'll enable some kind of integration with cloud services or something.

**Comment by FulI-Name** [comment]
I'm using One.com for hosting the website, and I thought the email thing was automatic that's why I was wondering. Like it said "easy to set up" and sents to email in config.js or whatever. Could I somehow make it work? Cause I'm pretty new to this. It looks really dumb that the email thing is there doing nothing and not even working

**Comment by FulI-Name** [comment]
So? Any ideas? Like how could I make it work or replace it with something else?
